let num1 = 10;
let num2 = 20;
console.log(num1.toExponential());
console.log(num1.toFixed());
console.log(num1.toPrecision());
console.log(num1.toString());
console.log(num1.valueOf());
console.log(num1.toLocaleString());
//console.log(num1.toSource());
//console.log(num1.toUTCString());
//console.log(num1.toTimeString());
console.log(Math.max(num1, num2));
console.log(Math.min(num1, num2));
console.log(Math.round(num1));
console.log(Math.floor(num1));
console.log(Math.ceil(num1));
console.log(Math.random());
console.log(Math.sqrt(num1));
console.log(Math.pow(num1, num2));
console.log(Math.abs(num1));
console.log(Math.sign(num1));
console.log(Math.trunc(num1));
console.log(Math.fround(num1));
console.log(Math.clz32(num1));
console.log(Math.cbrt(num1));
console.log(Math.hypot(num1, num2));
console.log(Math.imul(num1, num2));
console.log(Math.log(num1));
console.log(Math.log10(num1));
console.log(Math.log2(num1));
console.log(Math.exp(num1));
console.log(Math.expm1(num1));
console.log(Math.log1p(num1));
console.log("******************************")
console.log(Number.MAX_VALUE);
console.log(Number.MIN_VALUE);
console.log(Number.MAX_SAFE_INTEGER);
console.log(Number.MIN_SAFE_INTEGER);
console.log(Number.MAX_EXPONENT);
console.log(Number.MIN_EXPONENT);
console.log(Number.POSITIVE_INFINITY);
console.log(Number.NEGATIVE_INFINITY);
console.log(Number.NaN);
console.log(Number.EPSILON);
